// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCETu6saW9NNv5-4_ttNUD7T_j-oS19w6Q',
    appId: '1:549212009977:web:3ee97fceb1ced529ac7928',
    messagingSenderId: '549212009977',
    projectId: 'storage-product-2a98d',
    authDomain: 'storage-product-2a98d.firebaseapp.com',
    storageBucket: 'storage-product-2a98d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcI478YsKNbEycPBrmDa5FPyhOPSvO56g',
    appId: '1:549212009977:android:b260a9a1c533cc72ac7928',
    messagingSenderId: '549212009977',
    projectId: 'storage-product-2a98d',
    storageBucket: 'storage-product-2a98d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeQVS57kWYwQtYA-gnr3_Etn3m7nV3RbE',
    appId: '1:549212009977:ios:6715e028400338cdac7928',
    messagingSenderId: '549212009977',
    projectId: 'storage-product-2a98d',
    storageBucket: 'storage-product-2a98d.appspot.com',
    iosBundleId: 'com.example.lastfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeQVS57kWYwQtYA-gnr3_Etn3m7nV3RbE',
    appId: '1:549212009977:ios:f914e0fb7efcdf51ac7928',
    messagingSenderId: '549212009977',
    projectId: 'storage-product-2a98d',
    storageBucket: 'storage-product-2a98d.appspot.com',
    iosBundleId: 'com.example.lastfirebase.RunnerTests',
  );
}
